# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
gensim=3.8.0
keras-applications=1.0.8
keras-preprocessing=1.1.0
matplotlib=3.1.3
networkx=2.4
numpy=1.18.1
pandas=1.0.0
python=3.7.6
scikit-learn=0.22.1
scipy=1.4.1
seaborn=0.10.0
tensorflow=1.14.0
tensorflow-estimator=1.14.0
tqdm=4.42.0
